name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Electron app (Windows)
        run: npm run publish:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Notes
        id: release_notes
        run: |
          echo "Creating release notes..."
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "## Changes in this release" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "### New Features" >> $GITHUB_ENV
          echo "- Automatic updates via GitHub releases" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "### Improvements" >> $GITHUB_ENV
          echo "- Enhanced stability and performance" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV          
          echo "### Downloads" >> $GITHUB_ENV
          echo "- **Windows**: Download the .exe installer" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
